name: build-and-push
on:
  push:
    branches: [ "prod" ]   # <<--- importante: tu rama de despliegue

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write        # publicar a GHCR
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (tag latest + commit)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/payload-app:latest
            ghcr.io/${{ github.repository_owner }}/payload-app:${{ github.sha }}
          build-args: |
            NODE_ENV=production
